### ISSUE TITLE
Block forward bug 

### ISSUE THREAD

**Issue by Splixator** [jespertheend/splix#148] opened 2024-08-01 21:54 UTC
It's a glitsh that happens all the time when the player moves and change direction, looks like a split sec block forward, when there's noone around nothing bad happens but when this happens while fighting someone it will be a 100% death if he catches that glitsh and this happens all the time

**Comment by jespertheend** [comment] 2024-08-08 21:32
Thanks! This indeed looks like a duplicate of #93.
I'll close this but feel free to track that one for updates.

**Closed by jespertheend** 2024-08-08 21:32 UTC
